repos:
  - repo: local
    hooks:
      - id: check-author
        name: Ensure Commit Author
        entry: ./verify-author.sh
        language: system
        always_run: true
        pass_filenames: false
