project:
  title: "Data Science Rants"
  type: website
  output-dir: docs

website:
  title: "Data Science Rants"
  navbar:
    right:
      - about.qmd
      # - icon: github
      #   href: https://github.com/

format:
  html:
    theme:
      - sandstone
    css: styles.css
    grid:
      body-width: 600px
    toc: true
    code-block-border-left: true
    highlight-style: breezedark

execute:
  freeze: true
