project:
  type: website

website:
  title: "DS Rants"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - zephyr
      - brand
    css: styles.css
    grid:
      body-width: 600px
